---

# are we a postgresql server, or are we just applying the role to get the
# client libs installed?
pg_server: True
 
# is it a dedicated db server machine that does nothing else?
pg_dedicated: False

pg_ver: 9.2

